# Generated by Django 5.0.4 on 2024-06-01 06:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gioi_tinh',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten_gioitinh', models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='Nhan_vien',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cccd', models.CharField(max_length=20, unique=True)),
                ('ten_nhanvien', models.CharField(max_length=5)),
                ('dien_thoai', models.CharField(unique=True)),
                ('dia_chi', models.CharField(max_length=100)),
                ('ten_gioitinh', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quan_li_nhan_vien.gioi_tinh')),
            ],
        ),
    ]
